stages:
  - install
  - build
  - deploy

variables:
  NODE_VERSION: 18
  AWS_DEFAULT_REGION: your-aws-region # e.g., us-east-1
  S3_BUCKET_NAME: your-s3-bucket-name

before_script:
  - 'which nvm || (curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.38.0/install.sh | bash)'
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g @angular/cli

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - ng build --prod
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy_to_s3:
  stage: deploy
  script:
    - apt-get update -y && apt-get install -y python3-pip
    - pip3 install awscli
    - aws s3 sync ./dist/your-app-name s3://$S3_BUCKET_NAME --delete
  only:
    - master